@startuml aws-architecture

title aws-architecture
left to right direction

'===============================
' definition & import
'===============================
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v11.1/dist

!includeurl AWSPuml/AWSCommon.puml

!includeurl AWSPuml/General/Mobileclient.puml
!includeurl AWSPuml/GroupIcons/Cloudalt.puml
!includeurl AWSPuml/ApplicationIntegration/APIGateway.puml
!includeurl AWSPuml/Compute/Lambda.puml
!includeurl AWSPuml/Compute/EC2InstancewithCloudWatch.puml

!includeurl AWSPuml/AWSSimplified.puml

'===============================
' declaration
'===============================
Mobileclient(mobileClient, フロントアプリ, User client device)

Cloudalt(aws, " ", AWS) {
  APIGateway(apiGateway, "API Gateway", "API Gateway")
  Lambda(lambda, "Lambda", "Lambda")
  EC2InstancewithCloudWatch(watch, "CloudWatch", "CloudWatch")
}

node 仮想通貨取引所

'===============================
' relationship
'===============================
mobileClient --> apiGateway: REST API リクエスト
apiGateway <-- lambda: レスポンス
apiGateway --> lambda: Lambda関数の呼び出し
lambda --> watch: ログの出力
mobileClient <-- apiGateway: レスポンス

lambda -down-> 仮想通貨取引所: API call
lambda <-down- 仮想通貨取引所: レスポンス(取引情報など)

@enduml
